TOYS_PREFIX = "/toysy"
TOYS_TAG = "Toys"
TOYS_TABLE_NAME = "toys"

MIN_AGE = 0
MAX_AGE = 18
CAPACITY_MIN = 1
CAPACITY_MAX = 100
NAME_MIN_LENGTH = 2
NAME_MAX_LENGTH = 200

SLUG_MAX_LENGTH = 220
DESCRIPTION_SHORT_MAX = 500

DEFAULT_IS_ACTIVETE = True
DEFAULT_IS_FEATURE = False
DEFAULT_ORDER = 0
