"""create toys table

Revision ID: 5ed15047886b
Revises: 0d52adadfda0
Create Date: 2026-07-09 21:00:30.398366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed15047886b'
down_revision: Union[str, Sequence[str], None] = '0d52adadfda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('gallery_image_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('video_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['uploads.id'], name=op.f('fk_toys_cover_image_id_uploads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_toys'))
    )
    op.create_index(op.f('ix_toys_category'), 'toys', ['category'], unique=False)
    op.create_index(op.f('ix_toys_display_order'), 'toys', ['display_order'], unique=False)
    op.create_index(op.f('ix_toys_is_active'), 'toys', ['is_active'], unique=False)
    op.create_index(op.f('ix_toys_is_featured'), 'toys', ['is_featured'], unique=False)
    op.create_index(op.f('ix_toys_slug'), 'toys', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toys_slug'), table_name='toys')
    op.drop_index(op.f('ix_toys_is_featured'), table_name='toys')
    op.drop_index(op.f('ix_toys_is_active'), table_name='toys')
    op.drop_index(op.f('ix_toys_display_order'), table_name='toys')
    op.drop_index(op.f('ix_toys_category'), table_name='toys')
    op.drop_table('toys')
    # ### end Alembic commands ###
